[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nonebot-plugin-maimaidx"
version = "26.8.7"
authors = [
  { name="Yuri-YuzuChaN", email="806235364@qq.com" },
]
maintainers = [
  { name="AWMC TEAM" },
]
description = "maimaidx plugin for nonebot2"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "nonebot2>=2.0.0,<3.0.0",
    "nonebot-adapter-onebot>=2.2.2,<3.0.0",
    "nonebot-adapter-qq>=1.7.1,<2.0.0; python_version >= '3.10'",
    "nonebot-plugin-apscheduler>=0.3.0,<1.0.0",
    "aiofiles>=23.2.1,<25.0.0",
    "httpx>=0.23.1,<1.0.0",
    "pydantic>=2.0.0,<3.0.0",
    "pyecharts>=2.0.0,<3.0.0",
    "playwright>=1.52.0",
    "httpx-ws>=0.7.2,<1.0.0",
    "fastapi>=0.100.0,<1.0.0",
    "uvicorn>=0.23.0,<1.0.0",
    "PyYAML>=6.0.0,<7.0.0",
    "PyMySQL>=1.1.0,<2.0.0",
    "zxing-cpp>=3.0.0,<4.0.0",

    "pillow>=10.0.0,<11.0.0; python_version < '3.13'",
    "pillow>=11.0.0,<12.0.0; python_version >= '3.13'",

    "numpy==1.26.0; python_version < '3.10'",
    "numpy>=2.0.0,<3.0.0; python_version >= '3.10'",

    "openai>=1.0.0,<2.0.0",
]

[project.optional-dependencies]
feishu-ops = ["lark-oapi>=1.7.2,<2.0.0"]

[project.urls]
"Homepage" = "https://github.com/AWMC-TEAM/maimaiDX-QueryBot"
"Source" = "https://github.com/AWMC-TEAM/maimaiDX-QueryBot"
"Upstream" = "https://github.com/Yuri-YuzuChaN/maimaiDX"
"Bug Tracker" = "https://github.com/AWMC-TEAM/maimaiDX-QueryBot/issues"

[tool.setuptools.package-dir]
"nonebot_plugin_maimaidx" = "."

[tool.setuptools]
packages = [
    "nonebot_plugin_maimaidx",
    "nonebot_plugin_maimaidx.command",
    "nonebot_plugin_maimaidx.libraries",
    "nonebot_plugin_maimaidx.libraries.b50_analysis",
]

[tool.setuptools.package-data]
"nonebot_plugin_maimaidx" = ["maimaidxhelp.png", "scripts/*.py"]
"nonebot_plugin_maimaidx.libraries" = ["assets/*.json"]
