from .mai_alias import *
from .mai_announcement import *
from .mai_admin_runtime import *
from .mai_agreement import *
from .mai_account import *
from .mai_base import *
from .mai_break import *
from .mai_card import *
from .mai_b50_analysis import *
from .mai_roast_style import *
from .mai_feature import *
from .mai_guess import *
from .mai_letter import *
from .mai_lxns import *
from .mai_migration import *
from .mai_playcount import *
from .mai_song_rank import *
from .mai_score import *
from .mai_search import *
from .mai_table import *
from .mai_pmyx import *
from .mai_qq_bind import *
from .mai_forum_bind import *
from .mai_rank_course import *
from .mai_howto import *
from .mai_gate_guide import *
from .mai_draw_guess import *
from .mai_divingfish import *
