#!/bin/bash
set -e
cd /www/bot/awmc
source /www/bot/.venv/bin/activate
# 自适应并发：忙时降、闲时升；勿再写死 BG_FILL=0
export MAIMAIDX_CHART_ADAPTIVE=1
export MAIMAIDX_CHART_ADAPTIVE_INTERVAL=20
export MAIMAIDX_CHART_ADAPTIVE_WARMUP=60
export MAIMAIDX_CHART_RENDER_MIN=1
export MAIMAIDX_CHART_RENDER_MAX=3
export MAIMAIDX_CHART_BG_FILL_MIN=0
export MAIMAIDX_CHART_BG_FILL_MAX=1
export MAIMAIDX_CHART_BATCH_SONGS_MIN=1
export MAIMAIDX_CHART_BATCH_SONGS_MAX=2
export MAIMAIDX_CHART_FFMPEG_THREADS=1
export MAIMAIDX_CHART_CPU_POOL=3
export MAIMAIDX_CHART_ESTIMATE_SECONDS=180
export MAIMAIDX_CHART_VIDEO_PRESET=faster
# Demucs / PyTorch / BLAS 每次按 load 在 2～4 线程间选择，避免占满 32 核
export MAIMAIDX_AUDIO_CPU_THREADS_MIN=2
export MAIMAIDX_AUDIO_CPU_THREADS_MAX=4
export MAIMAIDX_AUDIO_ESTIMATE_SECONDS=150
# B50/图片合成走独立线程池，不再阻塞消息事件循环
export MAIMAIDX_IMAGE_WORKERS=8
unset MAIMAIDX_CHART_BG_FILL_WORKERS
unset MAIMAIDX_CHART_RENDER_WORKERS
unset MAIMAIDX_CHART_BATCH_SONGS
exec nb run
